version: '3'

services:
  app:
    build: .
    container_name: app_instagramClone
    ports:
      - '3333:3333'
    # environment:
    #   - DB_URL=database
    command: yarn dev
    # depends_on:
    #   - database
    volumes:
      - .:/usr/app
# Not used
# services:
# database:
#   image: kartoza/postgis
#   container_name: app_exemple
#   ports:
#     - '5432:5432'
